Updated XRM.Navigation.navigateTo to be up to date
delegateas/XrmDefinitelyTyped pull request #192
Opened 2020-07-08 13:56 UTC by KnethM

Fixes #182

2020-07-19 16:34 UTC, sudhip-git commented
Could you please confirm when this pull request will be merged

2020-07-24 15:14 UTC, magesoe commented
I am back from vacation next week, will look at this PR then

2020-07-31 07:38 UTC, magesoe requested changes
Love the PR, some minor changes. Do you agree with them?

2020-07-31 07:38 UTC, magesoe commented on src/XrmDefinitelyTyped/Resources/Extensions/xrm_ext_9-.d.ts
> +        navigateTo(pageInput: EntityRecord | EntityList | WebResource, navigationOptions: NavigationOptions): Promise<undefined>;
According to the documentation, navigationOptions is optional, so it should be navigationOptions?

2020-07-31 07:38 UTC, magesoe commented on src/XrmDefinitelyTyped/Resources/Extensions/xrm_ext_9-.d.ts
> +    type PageType = "entitylist" | "entityrecord" | "webresource";
Love the idea you had of extending a common interface, however it does pose a problem. Right now there is no connection between the chosen PageType and the type of extension. This means you are allowed to pass false parameters as this
```typescript
Xrm.Navigation.navigateTo({
      pageType: "entitylist",
      entityName: "",
      createFromEntity: {
        entityType: "",
        id: "",
        name: ""
      }
    })
```
The `pageType` variable should be moved to each declaration with a single allowed string that matches that declaration. For example `interface EntityList` should look like this 
```typescript
interface EntityList {
    pageType: "entitylist"
    ...
}
```
The reason why the base interface is removed is that pageType was the only common type among these interfaces. You should still keep the navigateTo function the same, with the union of the three interfaces.

2020-08-03 10:41 UTC, magesoe approved these changes

2020-08-10 12:24 UTC, merged